global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'pierrebroce@gmail.com'
  smtp_auth_username: 'pierrebroce@gmail.com'
  smtp_auth_password: 'xxxx xxxx xxxx'  # Voir plus bas
  smtp_require_tls: true

route:
  receiver: "gmail-receiver"
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: "gmail-receiver"
    email_configs:
      - to: "pierre.viland@ac-rennes.fr"

