server:
  http_listen_port: 9080  # Port d'écoute HTTP de Promtail
  grpc_listen_port: 0     # Désactivation de GRPC (optionnel)

clients:
  - url: http://loki:3100/loki/api/v1/push  # Adresse de Loki

positions:
  filename: /tmp/positions.yaml  # Fichier pour suivre la lecture des logs


scrape_configs:
  # Scrap tous les log de mon hôte
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log

  - job_name: nginx_container
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          container: nginxPV
          __path__: /var/lib/docker/containers/85268aa8e6cb59dd445a21d3796339e345f641f6e3e91b7606b7d495c342022d/85268aa8e6cb59dd445a21d3796339e345f641f6e3e91b7606b7d495c342022d-json.log

    pipeline_stages:
      - json:
          expressions:
            log: log

      - regex:
          expression: '"(?P<method>[A-Z]+)'

      - labels:
          method:

