server:
  http_listen_port: 3200

distributor:
  receivers:
    jaeger:
      protocols:
        grpc:
        thrift_binary:
        thrift_compact:
        thrift_http:

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces
